apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gpu-telemetry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gpu-telemetry
  template:
    metadata:
      labels:
        app: gpu-telemetry
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_PATH
              value: "/data/telemetry.db"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
